#!/usr/bin/env bash
# Magic Hat — Standalone Installer
# Copyright (c) 2026 George Scott Foley — MIT License
#
# Installs Magic Hat on an existing Fedora Server.
# Usage: curl -fsSL https://raw.githubusercontent.com/omegcrash/magic-hat/master/scripts/install.sh | sudo bash

set -euo pipefail

MAGICHAT_VERSION="0.1.0"
MAGICHAT_DIR="/opt/magichat"
MAGICHAT_USER="magichat"
REPO_URL="https://raw.githubusercontent.com/omegcrash/magic-hat/master"

echo "========================================="
echo "  Magic Hat Installer v${MAGICHAT_VERSION}"
echo "  Familiar AI Server Platform"
echo "========================================="
echo ""

# ── Preflight checks ────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (sudo)."
    exit 1
fi

if ! grep -qi "fedora" /etc/os-release 2>/dev/null; then
    echo "Warning: This installer is designed for Fedora Server."
    echo "Detected OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2)"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

echo "[1/8] Installing system packages..."
dnf install -y \
    postgresql-server postgresql-contrib \
    redis nginx certbot python3-certbot-nginx \
    podman podman-compose \
    fail2ban firewalld \
    python3.11 python3.11-pip python3.11-devel \
    dnf-automatic cronie rsync

echo "[2/8] Creating service user..."
if ! id "${MAGICHAT_USER}" &>/dev/null; then
    useradd --system --create-home --shell /bin/bash --comment "Magic Hat service" "${MAGICHAT_USER}"
fi

echo "[3/8] Installing Reflection..."
python3.11 -m pip install --upgrade pip
python3.11 -m pip install "reflection-agent[full]"

echo "[4/8] Configuring PostgreSQL..."
if [[ ! -f /var/lib/pgsql/data/PG_VERSION ]]; then
    postgresql-setup --initdb
fi
sed -i 's/ident/scram-sha-256/g' /var/lib/pgsql/data/pg_hba.conf
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '127.0.0.1'/" /var/lib/pgsql/data/postgresql.conf
systemctl enable --now postgresql

# Generate a random password for the database
DB_PASSWORD=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")
su - postgres -c "psql -c \"CREATE USER reflection WITH PASSWORD '${DB_PASSWORD}';\"" 2>/dev/null || \
su - postgres -c "psql -c \"ALTER USER reflection WITH PASSWORD '${DB_PASSWORD}';\""
su - postgres -c "psql -c \"CREATE DATABASE reflection OWNER reflection;\"" 2>/dev/null || true
su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE reflection TO reflection;\""

echo "[5/8] Configuring Redis..."
REDIS_PASSWORD=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")
mkdir -p /etc/redis/redis.conf.d
cat > /etc/redis/redis.conf.d/magichat.conf << EOF
bind 127.0.0.1
requirepass ${REDIS_PASSWORD}
maxmemory 256mb
maxmemory-policy allkeys-lru
save 900 1
save 300 10
save 60 10000
EOF
systemctl enable --now redis

echo "[6/8] Installing Magic Hat configs..."
mkdir -p "${MAGICHAT_DIR}"/{scripts,systemd,nginx,firewall,firstboot}
mkdir -p /etc/magichat
mkdir -p /var/backups/magichat
mkdir -p /var/log/magichat
mkdir -p /var/www/certbot
chown "${MAGICHAT_USER}:${MAGICHAT_USER}" /var/backups/magichat /var/log/magichat

# Generate Reflection env file
JWT_SECRET=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(48))")
ENCRYPTION_KEY=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")
cat > /etc/magichat/reflection.env << EOF
# Magic Hat — Reflection Environment
# Auto-generated by installer on $(date)
# Edit this file to configure Reflection.

DATABASE_URL=postgresql+asyncpg://reflection:${DB_PASSWORD}@127.0.0.1:5432/reflection
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379/0
JWT_SECRET=${JWT_SECRET}
FAMILIAR_ENCRYPTION_KEY=${ENCRYPTION_KEY}
REFLECTION_ENV=production
REFLECTION_HOST=127.0.0.1
REFLECTION_PORT=8000
REFLECTION_WORKERS=4
EOF
chmod 600 /etc/magichat/reflection.env
chown "${MAGICHAT_USER}:${MAGICHAT_USER}" /etc/magichat/reflection.env

# Download config files from repo
for f in systemd/reflection.service systemd/magichat-backup.service systemd/magichat-backup.timer; do
    curl -fsSL "${REPO_URL}/${f}" -o "${MAGICHAT_DIR}/${f}"
done
curl -fsSL "${REPO_URL}/nginx/reflection.conf" -o /etc/nginx/conf.d/reflection.conf
curl -fsSL "${REPO_URL}/firewall/jail.local" -o /etc/fail2ban/jail.local
curl -fsSL "${REPO_URL}/scripts/backup.sh" -o "${MAGICHAT_DIR}/scripts/backup.sh"
curl -fsSL "${REPO_URL}/scripts/magichat" -o /usr/local/bin/magichat
chmod +x "${MAGICHAT_DIR}/scripts/backup.sh" /usr/local/bin/magichat

# Install systemd units
cp "${MAGICHAT_DIR}"/systemd/*.service /etc/systemd/system/
cp "${MAGICHAT_DIR}"/systemd/*.timer /etc/systemd/system/

# Generate self-signed cert (certbot replaces this later)
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/pki/tls/private/magichat-selfsigned.key \
    -out /etc/pki/tls/certs/magichat-selfsigned.pem \
    -subj "/CN=magichat.local" 2>/dev/null

echo "[7/8] Enabling services..."
systemctl daemon-reload
systemctl enable reflection.service
systemctl enable magichat-backup.timer
systemctl enable fail2ban
systemctl enable nginx

# Security: dnf-automatic for security patches
sed -i 's/apply_updates = no/apply_updates = yes/' /etc/dnf/automatic.conf
sed -i 's/upgrade_type = default/upgrade_type = security/' /etc/dnf/automatic.conf
systemctl enable dnf-automatic.timer

echo "[8/8] Starting services..."
systemctl start reflection.service
systemctl start nginx
systemctl start fail2ban

echo ""
echo "========================================="
echo "  Magic Hat installed successfully!"
echo "========================================="
echo ""
echo "  Dashboard: https://$(hostname -f)"
echo "  Status:    magichat status"
echo ""
echo "  Next steps:"
echo "  1. Run 'magichat setup' to configure domain + TLS"
echo "  2. Run 'magichat admin' to create admin user"
echo ""
echo "  Config: /etc/magichat/reflection.env"
echo "  Logs:   journalctl -u reflection -f"
echo "  Backup: /var/backups/magichat/"
echo ""
