#!/usr/bin/env bash
# Magic Hat — Standalone Installer
# Copyright (c) 2026 George Scott Foley — MIT License
#
# Installs Magic Hat on an existing Fedora Server.
# Usage: curl -fsSL https://raw.githubusercontent.com/omegcrash/magic-hat/master/scripts/install.sh | sudo bash

set -euo pipefail

MAGICHAT_VERSION="0.3.0"
MAGICHAT_DIR="/opt/magichat"
MAGICHAT_USER="magichat"
REPO_URL="https://raw.githubusercontent.com/omegcrash/magic-hat/master"

echo "========================================="
echo "  Magic Hat Installer v${MAGICHAT_VERSION}"
echo "  Familiar AI Server Platform"
echo "========================================="
echo ""

# ── Preflight checks ────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (sudo)."
    exit 1
fi

if ! grep -qi "fedora" /etc/os-release 2>/dev/null; then
    echo "Warning: This installer is designed for Fedora Server."
    echo "Detected OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2)"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

echo "[1/12] Installing system packages..."
dnf install -y \
    postgresql-server postgresql-contrib \
    redis nginx certbot python3-certbot-nginx \
    podman podman-compose \
    fail2ban firewalld \
    python3.11 python3.11-pip python3.11-devel \
    dnf-automatic cronie rsync tar gzip unzip p7zip xz bzip2 \
    nano vim-enhanced tmux screen htop iotop sysstat git jq \
    curl wget bind-utils net-tools traceroute \
    lshw pciutils usbutils \
    libreoffice-headless libreoffice-writer libreoffice-calc libreoffice-impress \
    poppler-utils ImageMagick \
    ffmpeg sox mediainfo perl-Image-ExifTool \
    ghostscript pandoc tesseract tesseract-langpack-eng \
    smartmontools nvme-cli lm-sensors gnupg2 git-lfs \
    google-noto-sans-fonts liberation-fonts-common \
    liberation-mono-fonts liberation-sans-fonts liberation-serif-fonts \
    audit aide openssh-server \
    policycoreutils-python-utils setools-console \
    crypto-policies-scripts

echo "[2/12] Creating service user..."
if ! id "${MAGICHAT_USER}" &>/dev/null; then
    useradd --system --create-home --shell /bin/bash --comment "Magic Hat service" "${MAGICHAT_USER}"
fi

echo "[3/12] Installing Reflection..."
python3.11 -m pip install --upgrade pip
python3.11 -m pip install "reflection-agent[full]"

echo "[4/12] Configuring PostgreSQL..."
if [[ ! -f /var/lib/pgsql/data/PG_VERSION ]]; then
    postgresql-setup --initdb
fi
sed -i 's/ident/scram-sha-256/g' /var/lib/pgsql/data/pg_hba.conf
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '127.0.0.1'/" /var/lib/pgsql/data/postgresql.conf
systemctl enable --now postgresql

# Generate a random password for the database
DB_PASSWORD=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")
su - postgres -c "psql -c \"CREATE USER reflection WITH PASSWORD '${DB_PASSWORD}';\"" 2>/dev/null || \
su - postgres -c "psql -c \"ALTER USER reflection WITH PASSWORD '${DB_PASSWORD}';\""
su - postgres -c "psql -c \"CREATE DATABASE reflection OWNER reflection;\"" 2>/dev/null || true
su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE reflection TO reflection;\""

echo "[5/12] Configuring Redis..."
REDIS_PASSWORD=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")
mkdir -p /etc/redis/redis.conf.d
cat > /etc/redis/redis.conf.d/magichat.conf << EOF
bind 127.0.0.1
requirepass ${REDIS_PASSWORD}
maxmemory 256mb
maxmemory-policy allkeys-lru
save 900 1
save 300 10
save 60 10000
EOF
systemctl enable --now redis

echo "[6/12] Installing Magic Hat configs..."
mkdir -p "${MAGICHAT_DIR}"/{scripts,systemd,nginx,firewall,firstboot,lib}
mkdir -p /etc/magichat
mkdir -p /var/backups/magichat
mkdir -p /var/log/magichat
mkdir -p /var/www/certbot
chown "${MAGICHAT_USER}:${MAGICHAT_USER}" /var/backups/magichat /var/log/magichat

# Generate Reflection env file
JWT_SECRET=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(48))")
ENCRYPTION_KEY=$(python3.11 -c "import secrets; print(secrets.token_urlsafe(32))")
cat > /etc/magichat/reflection.env << EOF
# Magic Hat — Reflection Environment
# Auto-generated by installer on $(date)
# Edit this file to configure Reflection.

DATABASE_URL=postgresql+asyncpg://reflection:${DB_PASSWORD}@127.0.0.1:5432/reflection
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379/0
JWT_SECRET=${JWT_SECRET}
FAMILIAR_ENCRYPTION_KEY=${ENCRYPTION_KEY}
REFLECTION_ENV=production
REFLECTION_HOST=127.0.0.1
REFLECTION_PORT=8000
REFLECTION_WORKERS=4
EOF
chmod 600 /etc/magichat/reflection.env
chown "${MAGICHAT_USER}:${MAGICHAT_USER}" /etc/magichat/reflection.env

# Download config files from repo
for f in systemd/reflection.service systemd/magichat-backup.service systemd/magichat-backup.timer; do
    curl -fsSL "${REPO_URL}/${f}" -o "${MAGICHAT_DIR}/${f}"
done
curl -fsSL "${REPO_URL}/nginx/reflection.conf" -o /etc/nginx/conf.d/reflection.conf
curl -fsSL "${REPO_URL}/firewall/jail.local" -o /etc/fail2ban/jail.local
curl -fsSL "${REPO_URL}/scripts/backup.sh" -o "${MAGICHAT_DIR}/scripts/backup.sh"
curl -fsSL "${REPO_URL}/scripts/magichat" -o /usr/local/bin/magichat
curl -fsSL "${REPO_URL}/scripts/provider-health.sh" -o "${MAGICHAT_DIR}/scripts/provider-health.sh"
curl -fsSL "${REPO_URL}/scripts/configure-providers.sh" -o "${MAGICHAT_DIR}/scripts/configure-providers.sh"
curl -fsSL "${REPO_URL}/scripts/desktop.sh" -o "${MAGICHAT_DIR}/scripts/desktop.sh"
chmod +x "${MAGICHAT_DIR}/scripts/backup.sh" /usr/local/bin/magichat
chmod +x "${MAGICHAT_DIR}/scripts/provider-health.sh" "${MAGICHAT_DIR}/scripts/configure-providers.sh"
chmod +x "${MAGICHAT_DIR}/scripts/desktop.sh"

# Install systemd units
cp "${MAGICHAT_DIR}"/systemd/*.service /etc/systemd/system/
cp "${MAGICHAT_DIR}"/systemd/*.timer /etc/systemd/system/

# Generate self-signed cert (certbot replaces this later)
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/pki/tls/private/magichat-selfsigned.key \
    -out /etc/pki/tls/certs/magichat-selfsigned.pem \
    -subj "/CN=magichat.local" 2>/dev/null

echo "[7/12] Installing Ollama..."
# Install Ollama (official installer, runs as user not daemon)
curl -fsSL https://ollama.com/install.sh | OLLAMA_INSTALL_ONLY=1 sh 2>/dev/null || {
    echo "  WARN: Ollama auto-install failed. Install manually: https://ollama.com/download"
}

# Create model storage directory
mkdir -p /var/lib/magichat/models
chown "${MAGICHAT_USER}:${MAGICHAT_USER}" /var/lib/magichat/models

# Ollama environment
cat > /etc/magichat/ollama.env << 'EOF'
# Magic Hat — Ollama Configuration
# Edit to tune inference performance.
OLLAMA_HOST=127.0.0.1:11434
OLLAMA_MODELS=/var/lib/magichat/models
OLLAMA_NUM_PARALLEL=4
OLLAMA_MAX_LOADED_MODELS=2
OLLAMA_FLASH_ATTENTION=1
OLLAMA_KEEP_ALIVE=10m
EOF
chmod 644 /etc/magichat/ollama.env

# Install Ollama systemd unit + model check script
curl -fsSL "${REPO_URL}/systemd/magichat-ollama.service" -o /etc/systemd/system/magichat-ollama.service
curl -fsSL "${REPO_URL}/scripts/magichat-model-check" -o /usr/local/bin/magichat-model-check
chmod +x /usr/local/bin/magichat-model-check

# Add service user to GPU groups (needed for NVIDIA/AMD device access)
usermod -aG render "${MAGICHAT_USER}" 2>/dev/null || true
usermod -aG video "${MAGICHAT_USER}" 2>/dev/null || true

echo "[8/12] Detecting and configuring GPU..."
curl -fsSL "${REPO_URL}/scripts/detect-gpu.sh" -o "${MAGICHAT_DIR}/scripts/detect-gpu.sh"
chmod +x "${MAGICHAT_DIR}/scripts/detect-gpu.sh"
"${MAGICHAT_DIR}/scripts/detect-gpu.sh" --install || echo "  GPU setup skipped (CPU mode)"

echo "[9/12] Applying security hardening..."

# SSH hardening
curl -fsSL "${REPO_URL}/security/sshd_magichat.conf" -o /etc/ssh/sshd_config.d/99-magichat.conf
curl -fsSL "${REPO_URL}/security/ssh_banner" -o /etc/ssh/magichat_banner
systemctl reload sshd 2>/dev/null || true

# Kernel hardening
curl -fsSL "${REPO_URL}/security/sysctl-hardening.conf" -o /etc/sysctl.d/99-magichat.conf
sysctl --system >/dev/null 2>&1 || true

# Audit rules
curl -fsSL "${REPO_URL}/security/audit.rules" -o /etc/audit/rules.d/99-magichat.rules
systemctl enable auditd
systemctl start auditd 2>/dev/null || true

# seccomp + output filter
curl -fsSL "${REPO_URL}/security/seccomp-reflection.json" -o /etc/magichat/seccomp-reflection.json
curl -fsSL "${REPO_URL}/security/output-filter.conf" -o /etc/magichat/output-filter.conf

# fail2ban custom filters
mkdir -p /etc/fail2ban/filter.d
for f in nginx-blocked reflection-api-abuse reflection-auth; do
    curl -fsSL "${REPO_URL}/firewall/filter.d/${f}.conf" -o "/etc/fail2ban/filter.d/${f}.conf"
done

# Hardening script for ongoing audits
curl -fsSL "${REPO_URL}/security/hardening.sh" -o "${MAGICHAT_DIR}/security/hardening.sh"
mkdir -p "${MAGICHAT_DIR}/security"
chmod +x "${MAGICHAT_DIR}/security/hardening.sh"

# Disable core dumps
echo "* hard core 0" >> /etc/security/limits.conf

# TLS crypto policy — FUTURE (strongest)
update-crypto-policies --set FUTURE 2>/dev/null || true

echo "[10/12] Enabling services..."
# Install wizard + bridge
curl -fsSL "${REPO_URL}/firstboot/wizard.py" -o "${MAGICHAT_DIR}/firstboot/wizard.py"
curl -fsSL "${REPO_URL}/lib/familiar_bridge.py" -o "${MAGICHAT_DIR}/lib/familiar_bridge.py"
mkdir -p "${MAGICHAT_DIR}/firstboot"
curl -fsSL "${REPO_URL}/systemd/magichat-wizard.service" -o /etc/systemd/system/magichat-wizard.service
# Create first-boot marker
touch "${MAGICHAT_DIR}/.needs-firstboot"

systemctl daemon-reload
systemctl enable magichat-ollama.service
systemctl enable reflection.service
systemctl enable magichat-wizard.service
systemctl enable magichat-backup.timer
systemctl enable fail2ban
systemctl enable nginx

# Security: dnf-automatic for security patches
sed -i 's/apply_updates = no/apply_updates = yes/' /etc/dnf/automatic.conf
sed -i 's/upgrade_type = default/upgrade_type = security/' /etc/dnf/automatic.conf
systemctl enable dnf-automatic.timer

echo "[11/12] Starting services..."
systemctl start magichat-ollama.service
systemctl start reflection.service
systemctl start nginx
systemctl start fail2ban
systemctl start magichat-wizard.service

echo "[12/12] Initializing AIDE file integrity database..."
aide --init 2>/dev/null && \
    cp /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz 2>/dev/null || \
    echo "  (AIDE will initialize on next boot)"

echo ""
echo "========================================="
echo "  Magic Hat installed successfully!"
echo "========================================="
echo ""
echo "  Dashboard: https://$(hostname -f)"
echo "  Status:    magichat status"
echo ""
echo "  Next steps:"
echo "  1. Open http://$(hostname -I | awk '{print $1}'):8080 to run the setup wizard"
echo "     Or configure manually:"
echo "       magichat models pull   — download a model"
echo "       magichat setup         — configure domain + TLS"
echo "       magichat admin         — create admin user"
echo ""
echo "  Config: /etc/magichat/reflection.env"
echo "  Logs:   journalctl -u reflection -f"
echo "  Backup: /var/backups/magichat/"
echo ""
